name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "main", "dev" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO_NAME: lankavibe-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Log in Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Docker Setup 
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # --- BACKEND DEPLOYMENT ---
      
      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:latest ./backend
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:latest

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: lankavibe-backend
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:latest
          region: ${{ env.REGION }}
          flags: '--port=5000 --allow-unauthenticated' # Backend එක 5000න් දුවන නිසා
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
            SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            user=${{ secrets.EMAIL_USER }}
            pass=${{ secrets.EMAIL_PASS }}
            FRONTEND_URL=${{ secrets.PROD_FRONTEND_URL }}
            
      
      # --- FRONTEND DEPLOYMENT ---
      - name: Create Frontend .env
        run: |
          echo "VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY }}" > ./frontend/.env
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> ./frontend/.env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./frontend/.env
          echo "VITE_BACKEND_URL=${{ secrets.PROD_BACKEND_URL }}" >> ./frontend/.env

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:latest ./frontend
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:latest

      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: lankavibe-frontend
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:latest
          region: ${{ env.REGION }}
          flags: '--port=80 --allow-unauthenticated'